
        
        

import subprocess 
# Taking the list of 30 hosts as discussed in the classroom
hosts =hosts = ['wusa9.com', 'ca.gov', 'github.com', 'yahoo.in', 'sublime.com', 'dc.gov', 'ny.gov', \
          'nationsonline.org', 'whitehouse.gov', 'techcrunch.com',  'hongkiat.com', \
         'test.com', 'mit.edu', 'cmu.edu', 'ctrip.com',   ' medium.com', 'yahoo.com', 'yahoo.ru', \
          'naver.com',  'netflix.com' , 'youtube.com' , 'google.com', 'spotify.com', 'ntc.net.np']
# creating an empty hashmap for the output generated by the traceroute for the host [ hostname -> traceroute output]
host_out = {}
# running the traceroute command for each host
for i in range(0, 2):
    filename = hosts[i] + ".txt"
    curr_file = open(filename, 'w')
    for j in range(30):
		subprocess.call("sudo tcptraceroute " + hosts[i] + ">>" + filename , shell=True, stdout=subprocess.PIPE)
    curr_file.close()
    
    
      
        
        
